### ISSUE TITLE
Cannot Used in Mac OS High Sierra V10.13.1

### ISSUE THREAD

**Issue by putrabangga** [dhruvvyas90/ns-install-osx#1]
This script cannot used in Mac OS High Sierra V10.13.1, any solution for this?

**Comment by mtn** [comment]
@putrabangga Did you end up figuring this out or some workaround? Also, what problem were you running into (does it just not appear in the path)?

**Comment by dhruvvyas90** [comment]
@putrabangga : I don't work in this domain any more but if you find a solution, do send a PR to fix the problem. Would appreciate it. Thanks.

**Comment by arun98-mohan** [comment]
Sent a pull request.. hope this resolves this issue also

**Comment by arun98-mohan** [comment]
Also, i suggest you to run the commands in the script line by line so that you will be able to identify the error and rectify it.
Since Running it as a script, you may overlook some errors
