### ISSUE TITLE
wget unsupported scheme error

### ISSUE THREAD

**Issue by arun98-mohan** [dhruvvyas90/ns-install-osx#2]
When using wget, we get an error "Unsupported scheme", hence consider using curl <...> -o <o/p file name>

"dont use < >"

**Comment by dhruvvyas90** [comment]
@arun98-mohan : Do consider sending a pull request. I do not actively work in this domain and hence haven't looked at latest development for a while. Thanks.

**Comment by arun98-mohan** [comment]
Done

**Comment by dhruvvyas90** [comment]
@arun98-mohan Merged. Thanks for you PR.
